# syntax = edrevo/dockerfile-plus

INCLUDE+ Dockerfile.base

RUN mkdir /home/builder/optee
WORKDIR /home/builder/optee
COPY TEE_Initial_Configuration-Test_Suite_v2_0_0_2-2017_06_09.7z .
RUN repo init -u https://github.com/OP-TEE/manifest.git && repo sync -j10
WORKDIR /home/builder/optee/build
RUN make -j3 toolchains
